In [1]:
class Employee:
    
    employee_count =  0;
    total_salary = 0;
    
    def __init__(self, name, family , salary , department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1 
        Employee.total_salary += salary
        
        
    def calculate_average_salary(self):
        return Employee.total_salary/Employee.employee_count
        
class Fulltime_Employee(Employee):
    pass
            
              
e1 = Employee("Bhuvaneswar", "Marreddy", 90000, "IT")
print(e1.calculate_average_salary()) 

e2 = Employee("Jane", "Doe", 100000, "Marketing")
print(e2.calculate_average_salary()) 

e3 = Fulltime_Employee("Bob", "Smith", 70000, "Sales")
print(e3.calculate_average_salary()) 


90000.0
95000.0
86666.66666666667


Here Employee class with a data member employee_count to count the number of Employees, and total_salary to keep track of the total salary of all employees. The class also has a constructor __init__ that takes in the parameters name, family, salary, and department, and assigns them to the object's properties. The constructor also increments the employee_count by 1 and adds the salary to the total_salary for each employee that is created.

It also has a method calculate_average_salary which returns the average salary of all the employees by dividing the total_salary by the employee_count.

This code also creates a class Fulltime_Employee which inherits the properties of the Employee class using Fulltime_Employee(Employee).

Then the code creates an instance obj of the Employee class, obj1 and obj2 of the Fulltime_Employee class, and assigns values to their properties.

Finally, the code calls the calculate_average_salary method on the obj2 instance and print the result.

The code will run without any error, but the output might not be what is expected. The average salary will be incorrect because the total salary is not being reinitialized when a new employee is created, and the employee_count is not reinitialized. In this way, the total_salary would be the sum of all employees who ever existed and employee count would be the total number of employees who ever existed. So, the average salary would not be accurate for the current set of employees.

For the proper calculation of average salary, you should reinitialize the employee_count and total_salary in the constructor every time an employee object is created.

In [80]:
import numpy as np

initial_vector = np.random.uniform(1, 20, 20)

print("random vector of size 20")
print(initial_vector)

resized_array = initial_vector.reshape(4, 5)

print("After reshaping the array to 4 by 5")
print(resized_array)

final_array = np.where(resized_array == np.amax(resized_array, axis=1, keepdims=True), 0, resized_array)

print("final array output")
print(final_array)

random vector of size 20
[ 1.42502644 11.57424847 14.16089254 10.08087049 13.02198103  7.7372675
 15.68608333 19.94899845 11.27415491  8.28273852  1.69075634 18.85318784
  8.16373357 10.76843832  2.21991826  3.05850928  5.25456119  7.98100824
  9.5239159   4.5203491 ]
After reshaping the array to 4 by 5
[[ 1.42502644 11.57424847 14.16089254 10.08087049 13.02198103]
 [ 7.7372675  15.68608333 19.94899845 11.27415491  8.28273852]
 [ 1.69075634 18.85318784  8.16373357 10.76843832  2.21991826]
 [ 3.05850928  5.25456119  7.98100824  9.5239159   4.5203491 ]]
final array output
[[ 1.42502644 11.57424847  0.         10.08087049 13.02198103]
 [ 7.7372675  15.68608333  0.         11.27415491  8.28273852]
 [ 1.69075634  0.          8.16373357 10.76843832  2.21991826]
 [ 3.05850928  5.25456119  7.98100824  0.          4.5203491 ]]


Here np.random.uniform(1, 20, 20) creates a random vector of size 20 with floats in the range of 1-20. 

np.reshape(vec, (4, 5)) reshapes the vector to a 4x5 array. 

The line arr = np.where(arr == np.amax(arr, axis=1, keepdims=True), 0, arr) uses the numpy.where() function to replace the maximum element in each row of the array arr with 0.

The numpy.where() function is used to return elements, depending on the condition.

The condition here is arr == np.amax(resized_array, axis=1, keepdims=True), which returns a boolean array of the same shape as resized_array where the elements are True if the element of resized_array is equal to the maximum value of the corresponding row and False otherwise.

np.amax(resized_array, axis=1, keepdims=True) returns the maximum element of each row of arr along the specified axis (1), and keepdims=True is used to keep the dimensions of the resulting array with size 1 along the axis of the max.

so the numpy.where() function replaces all elements of arr that are equal to the maximum value of the corresponding row with 0 and keeps the other elements unchanged.
